### ISSUE TITLE
Todo for tool libs

### ISSUE THREAD

**Issue by noel-danielsson** [CASE-Association/Fusion360-CAM#1]
Todo:
- [ ]   Make reasonable structure for tool numbers
- [ ]  Make sure to reserve a tool number interval for user custom tools
- [ ]  Documentation and links on how to use the tool libraries.
- [ ]  Add all current tools to both lib and cnc local lib.
